name: Hello

on:
  push:
    branches: main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -l

      - name: Show current branch
        run: git branch
